# Introdução expressa de Pandas

### Dataset: negócios disponíveis no Yelp para a cidade de Toronto -- 2018.
### Este documento visa ilustrar recursos importantes de Pandas.

In [43]:
#Análise e manipulação de dados 
import pandas as pd

### Carregando os dados

In [45]:
# Caso esteja acessando na sua máquina
dfBusiToronto = pd.read_csv('businessToronto.csv')


# Uso no google colab (usar essas linhas - reconhecer o seu drive e substituir o caminho abaixo)
'''from google.colab import drive
drive.mount('/content/drive')

#após a autorização, copie o caminho do arquivo no seu drive (ache o arquivo e clique com o botão direito)
#dfBusiToronto = pd.read_csv('/content/drive/MyDrive/MineracaoDados/ConhecendoDados/businessToronto.csv')
'''

"from google.colab import drive\ndrive.mount('/content/drive')\n\n#após a autorização, copie o caminho do arquivo no seu drive (ache o arquivo e clique com o botão direito)\n#dfBusiToronto = pd.read_csv('/content/drive/MyDrive/MineracaoDados/ConhecendoDados/businessToronto.csv')\n"

### Manipulações básicas

In [46]:
dfBusiToronto

,_id,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours,loc
0,5f8a33caf961c6b3e3c5f018,zSpQmEBvRe3IhTUlMSA6HQ,Totum Life Science,"445 King Street W, Suite 101",Toronto,ON,M5V 1K4,43.645041,-79.395799,4.0,23,1,"{'AcceptsInsurance': 'True', 'ByAppointmentOnl...","Trainers, Health & Medical, Active Life, Physi...","{'Monday': '6:0-22:0', 'Tuesday': '6:0-22:0', ...","{'type': 'Point', 'coordinates': [-79.3957986,..."
1,5f8a33caf961c6b3e3c5f020,NDuUMJfrWk52RA-H-OtrpA,Bolt Fresh Bar,1170 Queen Street W,Toronto,ON,M6J 1J5,43.642889,-79.425429,3.0,57,1,"{'WiFi': ""u'no'"", 'BikeParking': 'True', 'Rest...","Juice Bars & Smoothies, Food, Restaurants, Fas...","{'Monday': '8:0-21:0', 'Tuesday': '8:0-21:0', ...","{'type': 'Point', 'coordinates': [-79.4254291,..."
2,5f8a33caf961c6b3e3c5f024,C9keC4mWuXdl2mYFHZXudQ,Uncle Otis Clothing,26 Bellair St,Toronto,ON,M5R 2C7,43.670744,-79.391385,5.0,12,1,"{'RestaurantsPriceRange2': '3', 'BusinessParki...","Fashion, Sporting Goods, Men's Clothing, Shopp...","{'Monday': '11:30-19:0', 'Tuesday': '11:30-19:...","{'type': 'Point', 'coordinates': [-79.3913851,..."
3,5f8a33caf961c6b3e3c5f027,SP_YXIEwkFPPl_9anCYmpQ,The Steady Cafe & Bar,1051 Bloor Street W,Toronto,ON,M6H 1M4,43.660494,-79.432099,3.5,29,0,"{'BusinessParking': ""{'garage': False, 'street...","Restaurants, Nightlife, Breakfast & Brunch, Ve...","{'Tuesday': '9:0-18:0', 'Wednesday': '9:0-18:0...","{'type': 'Point', 'coordinates': [-79.432099, ..."
4,5f8a33caf961c6b3e3c5f02f,C9oCPomVP0mtKa8z99E3gg,Bakery Gateau,"865 York Mills Road, Unit 1",Toronto,ON,M3B 1Y6,43.754093,-79.349548,4.5,8,1,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food","{'Monday': '9:0-20:0', 'Tuesday': '9:0-20:0', ...","{'type': 'Point', 'coordinates': [-79.3495479,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18901,5f8a33cff961c6b3e3c8e031,5XwfpotCAvDzPyAulk_m5A,Starbucks,1 Adelaide St E,Toronto,ON,M5C 2V9,43.650161,-79.377797,3.5,6,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsPri...","Coffee & Tea, Food",NaN,"{'type': 'Point', 'coordinates': [-79.3777975,..."
18902,5f8a33cff961c6b3e3c8e03d,_mo-QIcmJgUwcjeunAwtew,Espinosa Master Tailor,"221 Davenport Rd Toronto, ON M5R IJ3, Unit 9",Toronto,ON,M4W 1J5,43.674761,-79.395690,4.0,6,1,"{'RestaurantsPriceRange2': '3', 'WheelchairAcc...","Professional Services, Men's Clothing, Shoppin...","{'Monday': '9:0-17:0', 'Tuesday': '9:0-17:0', ...","{'type': 'Point', 'coordinates': [-79.39569033..."
18903,5f8a33cff961c6b3e3c8e04f,lo8WwqKogC-kz4toRvkdUQ,KOKO! Share Bar,81 Yorkville Avenue,Toronto,ON,M5R 1C1,43.670948,-79.391502,3.5,47,1,"{'RestaurantsTakeOut': 'True', 'Alcohol': ""u'f...","Korean, Japanese, Asian Fusion, Restaurants","{'Monday': '11:30-22:30', 'Tuesday': '11:30-22...","{'type': 'Point', 'coordinates': [-79.3915019,..."
18904,5f8a33cff961c6b3e3c8e057,oS0CnUbyv0GUoD3L8_3UPQ,Thai Fantasy,578 Yonge Street,Toronto,ON,M4Y 1Z3,43.665120,-79.384809,4.0,113,1,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai","{'Monday': '0:0-0:0', 'Tuesday': '11:0-23:0', ...","{'type': 'Point', 'coordinates': [-79.3848093,..."
18905,5f8a33cff961c6b3e3c8e058,12yF9Vz4vH5DXcSeiUt6zw,LTS Nails,540 Eglinton Avenue W,Toronto,ON,M5N,43.703476,-79.414548,4.5,12,1,"{'BusinessParking': ""{'garage': False, 'street...","Nail Salons, Beauty & Spas","{'Monday': '0:0-0:0', 'Tuesday': '10:0-19:0', ...","{'type': 'Point', 'coordinates': [-79.4145483,..."

In [64]:
dfBusiToronto.tail()

,_id,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours,loc
18901,5f8a33cff961c6b3e3c8e031,5XwfpotCAvDzPyAulk_m5A,Starbucks,1 Adelaide St E,Toronto,ON,M5C 2V9,43.650161,-79.377797,3.5,6,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsPri...","Coffee & Tea, Food",NaN,"{'type': 'Point', 'coordinates': [-79.3777975,..."
18902,5f8a33cff961c6b3e3c8e03d,_mo-QIcmJgUwcjeunAwtew,Espinosa Master Tailor,"221 Davenport Rd Toronto, ON M5R IJ3, Unit 9",Toronto,ON,M4W 1J5,43.674761,-79.395690,4.0,6,1,"{'RestaurantsPriceRange2': '3', 'WheelchairAcc...","Professional Services, Men's Clothing, Shoppin...","{'Monday': '9:0-17:0', 'Tuesday': '9:0-17:0', ...","{'type': 'Point', 'coordinates': [-79.39569033..."
18903,5f8a33cff961c6b3e3c8e04f,lo8WwqKogC-kz4toRvkdUQ,KOKO! Share Bar,81 Yorkville Avenue,Toronto,ON,M5R 1C1,43.670948,-79.391502,3.5,47,1,"{'RestaurantsTakeOut': 'True', 'Alcohol': ""u'f...","Korean, Japanese, Asian Fusion, Restaurants","{'Monday': '11:30-22:30', 'Tuesday': '11:30-22...","{'type': 'Point', 'coordinates': [-79.3915019,..."
18904,5f8a33cff961c6b3e3c8e057,oS0CnUbyv0GUoD3L8_3UPQ,Thai Fantasy,578 Yonge Street,Toronto,ON,M4Y 1Z3,43.665120,-79.384809,4.0,113,1,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai","{'Monday': '0:0-0:0', 'Tuesday': '11:0-23:0', ...","{'type': 'Point', 'coordinates': [-79.3848093,..."
18905,5f8a33cff961c6b3e3c8e058,12yF9Vz4vH5DXcSeiUt6zw,LTS Nails,540 Eglinton Avenue W,Toronto,ON,M5N,43.703476,-79.414548,4.5,12,1,"{'BusinessParking': ""{'garage': False, 'street...","Nail Salons, Beauty & Spas","{'Monday': '0:0-0:0', 'Tuesday': '10:0-19:0', ...","{'type': 'Point', 'coordinates': [-79.4145483,..."

In [51]:
dfBusiToronto['name']

0            Totum Life Science
1                Bolt Fresh Bar
2           Uncle Otis Clothing
3         The Steady Cafe & Bar
4                 Bakery Gateau
                  ...
18901                 Starbucks
18902    Espinosa Master Tailor
18903           KOKO! Share Bar
18904              Thai Fantasy
18905                 LTS Nails
Name: name, Length: 18906, dtype: object

In [50]:
dfBusiToronto.loc[:,'name']

0            Totum Life Science
1                Bolt Fresh Bar
2           Uncle Otis Clothing
3         The Steady Cafe & Bar
4                 Bakery Gateau
                  ...
18901                 Starbucks
18902    Espinosa Master Tailor
18903           KOKO! Share Bar
18904              Thai Fantasy
18905                 LTS Nails
Name: name, Length: 18906, dtype: object

In [55]:
# Mostra a estrutura do dataframe (linhas, colunas)
dfBusiToronto.shape

(18906, 16)

In [56]:
# Remover a última coluna do dataframe - nome: "loc"
dfBusiToronto = dfBusiToronto.drop(['loc'], axis=1)
dfBusiToronto

,_id,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,5f8a33caf961c6b3e3c5f018,zSpQmEBvRe3IhTUlMSA6HQ,Totum Life Science,"445 King Street W, Suite 101",Toronto,ON,M5V 1K4,43.645041,-79.395799,4.0,23,1,"{'AcceptsInsurance': 'True', 'ByAppointmentOnl...","Trainers, Health & Medical, Active Life, Physi...","{'Monday': '6:0-22:0', 'Tuesday': '6:0-22:0', ..."
1,5f8a33caf961c6b3e3c5f020,NDuUMJfrWk52RA-H-OtrpA,Bolt Fresh Bar,1170 Queen Street W,Toronto,ON,M6J 1J5,43.642889,-79.425429,3.0,57,1,"{'WiFi': ""u'no'"", 'BikeParking': 'True', 'Rest...","Juice Bars & Smoothies, Food, Restaurants, Fas...","{'Monday': '8:0-21:0', 'Tuesday': '8:0-21:0', ..."
2,5f8a33caf961c6b3e3c5f024,C9keC4mWuXdl2mYFHZXudQ,Uncle Otis Clothing,26 Bellair St,Toronto,ON,M5R 2C7,43.670744,-79.391385,5.0,12,1,"{'RestaurantsPriceRange2': '3', 'BusinessParki...","Fashion, Sporting Goods, Men's Clothing, Shopp...","{'Monday': '11:30-19:0', 'Tuesday': '11:30-19:..."
3,5f8a33caf961c6b3e3c5f027,SP_YXIEwkFPPl_9anCYmpQ,The Steady Cafe & Bar,1051 Bloor Street W,Toronto,ON,M6H 1M4,43.660494,-79.432099,3.5,29,0,"{'BusinessParking': ""{'garage': False, 'street...","Restaurants, Nightlife, Breakfast & Brunch, Ve...","{'Tuesday': '9:0-18:0', 'Wednesday': '9:0-18:0..."
4,5f8a33caf961c6b3e3c5f02f,C9oCPomVP0mtKa8z99E3gg,Bakery Gateau,"865 York Mills Road, Unit 1",Toronto,ON,M3B 1Y6,43.754093,-79.349548,4.5,8,1,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food","{'Monday': '9:0-20:0', 'Tuesday': '9:0-20:0', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18901,5f8a33cff961c6b3e3c8e031,5XwfpotCAvDzPyAulk_m5A,Starbucks,1 Adelaide St E,Toronto,ON,M5C 2V9,43.650161,-79.377797,3.5,6,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsPri...","Coffee & Tea, Food",NaN
18902,5f8a33cff961c6b3e3c8e03d,_mo-QIcmJgUwcjeunAwtew,Espinosa Master Tailor,"221 Davenport Rd Toronto, ON M5R IJ3, Unit 9",Toronto,ON,M4W 1J5,43.674761,-79.395690,4.0,6,1,"{'RestaurantsPriceRange2': '3', 'WheelchairAcc...","Professional Services, Men's Clothing, Shoppin...","{'Monday': '9:0-17:0', 'Tuesday': '9:0-17:0', ..."
18903,5f8a33cff961c6b3e3c8e04f,lo8WwqKogC-kz4toRvkdUQ,KOKO! Share Bar,81 Yorkville Avenue,Toronto,ON,M5R 1C1,43.670948,-79.391502,3.5,47,1,"{'RestaurantsTakeOut': 'True', 'Alcohol': ""u'f...","Korean, Japanese, Asian Fusion, Restaurants","{'Monday': '11:30-22:30', 'Tuesday': '11:30-22..."
18904,5f8a33cff961c6b3e3c8e057,oS0CnUbyv0GUoD3L8_3UPQ,Thai Fantasy,578 Yonge Street,Toronto,ON,M4Y 1Z3,43.665120,-79.384809,4.0,113,1,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai","{'Monday': '0:0-0:0', 'Tuesday': '11:0-23:0', ..."
18905,5f8a33cff961c6b3e3c8e058,12yF9Vz4vH5DXcSeiUt6zw,LTS Nails,540 Eglinton Avenue W,Toronto,ON,M5N,43.703476,-79.414548,4.5,12,1,"{'BusinessParking': ""{'garage': False, 'street...","Nail Salons, Beauty & Spas","{'Monday': '0:0-0:0', 'Tuesday': '10:0-19:0', ..."

In [60]:
#Adicionar uma nova coluna

dfBusiToronto['teste'] = 0

dfBusiToronto

,_id,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours,teste
0,5f8a33caf961c6b3e3c5f018,zSpQmEBvRe3IhTUlMSA6HQ,Totum Life Science,"445 King Street W, Suite 101",Toronto,ON,M5V 1K4,43.645041,-79.395799,4.0,23,1,"{'AcceptsInsurance': 'True', 'ByAppointmentOnl...","Trainers, Health & Medical, Active Life, Physi...","{'Monday': '6:0-22:0', 'Tuesday': '6:0-22:0', ...",0
1,5f8a33caf961c6b3e3c5f020,NDuUMJfrWk52RA-H-OtrpA,Bolt Fresh Bar,1170 Queen Street W,Toronto,ON,M6J 1J5,43.642889,-79.425429,3.0,57,1,"{'WiFi': ""u'no'"", 'BikeParking': 'True', 'Rest...","Juice Bars & Smoothies, Food, Restaurants, Fas...","{'Monday': '8:0-21:0', 'Tuesday': '8:0-21:0', ...",0
2,5f8a33caf961c6b3e3c5f024,C9keC4mWuXdl2mYFHZXudQ,Uncle Otis Clothing,26 Bellair St,Toronto,ON,M5R 2C7,43.670744,-79.391385,5.0,12,1,"{'RestaurantsPriceRange2': '3', 'BusinessParki...","Fashion, Sporting Goods, Men's Clothing, Shopp...","{'Monday': '11:30-19:0', 'Tuesday': '11:30-19:...",0
3,5f8a33caf961c6b3e3c5f027,SP_YXIEwkFPPl_9anCYmpQ,The Steady Cafe & Bar,1051 Bloor Street W,Toronto,ON,M6H 1M4,43.660494,-79.432099,3.5,29,0,"{'BusinessParking': ""{'garage': False, 'street...","Restaurants, Nightlife, Breakfast & Brunch, Ve...","{'Tuesday': '9:0-18:0', 'Wednesday': '9:0-18:0...",0
4,5f8a33caf961c6b3e3c5f02f,C9oCPomVP0mtKa8z99E3gg,Bakery Gateau,"865 York Mills Road, Unit 1",Toronto,ON,M3B 1Y6,43.754093,-79.349548,4.5,8,1,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food","{'Monday': '9:0-20:0', 'Tuesday': '9:0-20:0', ...",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18901,5f8a33cff961c6b3e3c8e031,5XwfpotCAvDzPyAulk_m5A,Starbucks,1 Adelaide St E,Toronto,ON,M5C 2V9,43.650161,-79.377797,3.5,6,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsPri...","Coffee & Tea, Food",NaN,0
18902,5f8a33cff961c6b3e3c8e03d,_mo-QIcmJgUwcjeunAwtew,Espinosa Master Tailor,"221 Davenport Rd Toronto, ON M5R IJ3, Unit 9",Toronto,ON,M4W 1J5,43.674761,-79.395690,4.0,6,1,"{'RestaurantsPriceRange2': '3', 'WheelchairAcc...","Professional Services, Men's Clothing, Shoppin...","{'Monday': '9:0-17:0', 'Tuesday': '9:0-17:0', ...",0
18903,5f8a33cff961c6b3e3c8e04f,lo8WwqKogC-kz4toRvkdUQ,KOKO! Share Bar,81 Yorkville Avenue,Toronto,ON,M5R 1C1,43.670948,-79.391502,3.5,47,1,"{'RestaurantsTakeOut': 'True', 'Alcohol': ""u'f...","Korean, Japanese, Asian Fusion, Restaurants","{'Monday': '11:30-22:30', 'Tuesday': '11:30-22...",0
18904,5f8a33cff961c6b3e3c8e057,oS0CnUbyv0GUoD3L8_3UPQ,Thai Fantasy,578 Yonge Street,Toronto,ON,M4Y 1Z3,43.665120,-79.384809,4.0,113,1,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai","{'Monday': '0:0-0:0', 'Tuesday': '11:0-23:0', ...",0
18905,5f8a33cff961c6b3e3c8e058,12yF9Vz4vH5DXcSeiUt6zw,LTS Nails,540 Eglinton Avenue W,Toronto,ON,M5N,43.703476,-79.414548,4.5,12,1,"{'BusinessParking': ""{'garage': False, 'street...","Nail Salons, Beauty & Spas","{'Monday': '0:0-0:0', 'Tuesday': '10:0-19:0', ...",0

#### Apply + Lambda

In [63]:
#Apply aplica uma função ao longo de um eixo do DataFrame.

dfBusiToronto.loc[:,['stars', 'review_count']].apply(lambda x: x+10)

       stars  review_count
0       14.0            33
1       13.0            67
2       15.0            22
3       13.5            39
4       14.5            18
...      ...           ...
18901   13.5            16
18902   14.0            16
18903   13.5            57
18904   14.0           123
18905   14.5            22

[18906 rows x 2 columns]

### Filtro

In [65]:
corte = dfBusiToronto['review_count'] > 100

dfBusiToronto[corte]

,_id,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours,teste
19,5f8a33caf961c6b3e3c5f0b5,c35qzLN6ItDpVIoj2uQW4Q,Ravi Soups,322 Adelaide Street W,Toronto,ON,M5V 1R1,43.647585,-79.392032,4.5,332,1,"{'Alcohol': ""u'beer_and_wine'"", 'BikeParking':...","Soup, Restaurants, Sandwiches","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",10
22,5f8a33caf961c6b3e3c5f0c2,i6hWP3si97eKQl_JyK8L3w,Hilton Toronto,145 Richmond Street W,Toronto,ON,M5H 2L2,43.649612,-79.385447,3.5,131,1,"{'RestaurantsPriceRange2': '3', 'WiFi': ""'free...","Hotels, Event Planning & Services, Hotels & Tr...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",10
50,5f8a33caf961c6b3e3c5f218,h_ypoQ2rmwX8UGSmohsGiQ,Maman,"1 First Canadian Place, Food Terrace, Upper Level",Toronto,ON,M5X 1C1,43.648977,-79.382409,3.5,122,1,"{'OutdoorSeating': 'True', 'RestaurantsDeliver...","Event Planning & Services, American (Tradition...","{'Monday': '0:0-0:0', 'Tuesday': '7:0-18:0', '...",10
54,5f8a33caf961c6b3e3c5f24b,j_pi7HWSARbfKabuPRsXbw,The Ten Spot - Queen West,749 Queen Street W,Toronto,ON,M6J 1G1,43.646324,-79.407152,3.5,108,1,"{'RestaurantsPriceRange2': '2', 'BusinessParki...","Waxing, Nail Salons, Hair Removal, Beauty & Sp...","{'Monday': '8:0-20:0', 'Tuesday': '8:0-20:0', ...",10
72,5f8a33caf961c6b3e3c5f2d5,eoG9zP7xxsDHVM0kJYrvkw,The Shameful Tiki Room,1378 Queen W,Toronto,ON,M6K 1L7,43.641439,-79.433303,4.0,148,1,"{'Music': ""{'dj': False, 'background_music': T...","Cocktail Bars, Bars, Tiki Bars, Nightlife","{'Monday': '17:0-1:0', 'Tuesday': '17:0-1:0', ...",10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18792,5f8a33cff961c6b3e3c8dbbc,kYD9E14AijONhJ7rFsyLrg,The Elm Tree Restaurant,43 Elm Street,Toronto,ON,M5G 1H1,43.657287,-79.383697,4.5,220,1,"{'RestaurantsPriceRange2': '2', 'RestaurantsAt...","Modern European, Restaurants, Mediterranean","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",10
18822,5f8a33cff961c6b3e3c8dd45,An-JJle53UMHokU4MwFktg,Deer Garden Signatures,"633 Silver Star Boulevard ., Unit 125",Toronto,ON,M1V 5N1,43.822058,-79.298592,3.5,150,1,"{'RestaurantsReservations': 'True', 'Restauran...","Chinese, Restaurants","{'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'...",10
18850,5f8a33cff961c6b3e3c8de85,B01pO_pI_8AOfEsukGNg-Q,100 Percent Korean,4779 Steeles Avenue E,Toronto,ON,M1V,43.825482,-79.298528,4.5,191,1,"{'RestaurantsAttire': ""u'casual'"", 'Alcohol': ...","Korean, Restaurants","{'Monday': '12:0-21:0', 'Wednesday': '11:30-21...",10
18854,5f8a33cff961c6b3e3c8de96,_81fRJ9m8Fn1s8ixPun46A,Union Social Eatery,4899 Yonge Street,Toronto,ON,M2N 5N4,43.763904,-79.411188,3.5,219,1,"{'HasTV': 'True', 'Alcohol': ""u'full_bar'"", 'R...","Restaurants, Gastropubs, Burgers, Barbeque","{'Monday': '11:0-0:0', 'Tuesday': '11:0-0:0', ...",10
18904,5f8a33cff961c6b3e3c8e057,oS0CnUbyv0GUoD3L8_3UPQ,Thai Fantasy,578 Yonge Street,Toronto,ON,M4Y 1Z3,43.665120,-79.384809,4.0,113,1,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai","{'Monday': '0:0-0:0', 'Tuesday': '11:0-23:0', ...",10

In [75]:
#Adicionando um novo atributio com base em um filtro

dfBusiToronto['popular'] = dfBusiToronto['review_count'] > 300

dfBusiToronto

,_id,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours,teste,popular,t
0,5f8a33caf961c6b3e3c5f018,zSpQmEBvRe3IhTUlMSA6HQ,Totum Life Science,"445 King Street W, Suite 101",Toronto,ON,M5V 1K4,43.645041,-79.395799,4.0,23,1,"{'AcceptsInsurance': 'True', 'ByAppointmentOnl...","Trainers, Health & Medical, Active Life, Physi...","{'Monday': '6:0-22:0', 'Tuesday': '6:0-22:0', ...",10,False,False
1,5f8a33caf961c6b3e3c5f020,NDuUMJfrWk52RA-H-OtrpA,Bolt Fresh Bar,1170 Queen Street W,Toronto,ON,M6J 1J5,43.642889,-79.425429,3.0,57,1,"{'WiFi': ""u'no'"", 'BikeParking': 'True', 'Rest...","Juice Bars & Smoothies, Food, Restaurants, Fas...","{'Monday': '8:0-21:0', 'Tuesday': '8:0-21:0', ...",10,False,False
2,5f8a33caf961c6b3e3c5f024,C9keC4mWuXdl2mYFHZXudQ,Uncle Otis Clothing,26 Bellair St,Toronto,ON,M5R 2C7,43.670744,-79.391385,5.0,12,1,"{'RestaurantsPriceRange2': '3', 'BusinessParki...","Fashion, Sporting Goods, Men's Clothing, Shopp...","{'Monday': '11:30-19:0', 'Tuesday': '11:30-19:...",10,False,False
3,5f8a33caf961c6b3e3c5f027,SP_YXIEwkFPPl_9anCYmpQ,The Steady Cafe & Bar,1051 Bloor Street W,Toronto,ON,M6H 1M4,43.660494,-79.432099,3.5,29,0,"{'BusinessParking': ""{'garage': False, 'street...","Restaurants, Nightlife, Breakfast & Brunch, Ve...","{'Tuesday': '9:0-18:0', 'Wednesday': '9:0-18:0...",10,False,False
4,5f8a33caf961c6b3e3c5f02f,C9oCPomVP0mtKa8z99E3gg,Bakery Gateau,"865 York Mills Road, Unit 1",Toronto,ON,M3B 1Y6,43.754093,-79.349548,4.5,8,1,"{'RestaurantsDelivery': 'False', 'RestaurantsP...","Bakeries, Food","{'Monday': '9:0-20:0', 'Tuesday': '9:0-20:0', ...",10,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18901,5f8a33cff961c6b3e3c8e031,5XwfpotCAvDzPyAulk_m5A,Starbucks,1 Adelaide St E,Toronto,ON,M5C 2V9,43.650161,-79.377797,3.5,6,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsPri...","Coffee & Tea, Food",NaN,10,False,False
18902,5f8a33cff961c6b3e3c8e03d,_mo-QIcmJgUwcjeunAwtew,Espinosa Master Tailor,"221 Davenport Rd Toronto, ON M5R IJ3, Unit 9",Toronto,ON,M4W 1J5,43.674761,-79.395690,4.0,6,1,"{'RestaurantsPriceRange2': '3', 'WheelchairAcc...","Professional Services, Men's Clothing, Shoppin...","{'Monday': '9:0-17:0', 'Tuesday': '9:0-17:0', ...",10,False,False
18903,5f8a33cff961c6b3e3c8e04f,lo8WwqKogC-kz4toRvkdUQ,KOKO! Share Bar,81 Yorkville Avenue,Toronto,ON,M5R 1C1,43.670948,-79.391502,3.5,47,1,"{'RestaurantsTakeOut': 'True', 'Alcohol': ""u'f...","Korean, Japanese, Asian Fusion, Restaurants","{'Monday': '11:30-22:30', 'Tuesday': '11:30-22...",10,False,False
18904,5f8a33cff961c6b3e3c8e057,oS0CnUbyv0GUoD3L8_3UPQ,Thai Fantasy,578 Yonge Street,Toronto,ON,M4Y 1Z3,43.665120,-79.384809,4.0,113,1,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Restaurants, Thai","{'Monday': '0:0-0:0', 'Tuesday': '11:0-23:0', ...",10,False,False
18905,5f8a33cff961c6b3e3c8e058,12yF9Vz4vH5DXcSeiUt6zw,LTS Nails,540 Eglinton Avenue W,Toronto,ON,M5N,43.703476,-79.414548,4.5,12,1,"{'BusinessParking': ""{'garage': False, 'street...","Nail Salons, Beauty & Spas","{'Monday': '0:0-0:0', 'Tuesday': '10:0-19:0', ...",10,False,False